<?php

# Migración para la tabla `configuracion`

return [
    "CREATE TABLE IF NOT EXISTS `{$prefix}configuracion` (
		`tscript_id` INT PRIMARY KEY,
		`titulo` VARCHAR(64) UNIQUE NOT NULL DEFAULT '',
		`slogan` VARCHAR(128) UNIQUE NOT NULL DEFAULT '',
		`url` VARCHAR(255) NOT NULL DEFAULT '',
		`email` VARCHAR(255) UNIQUE NOT NULL DEFAULT '',
		`banner` VARCHAR(255) NOT NULL DEFAULT '',
		`tema` VARCHAR(30) NOT NULL DEFAULT 'default',
		`c_allow_ticket` TINYINT NOT NULL DEFAULT 0,
		`c_allow_foro` TINYINT NOT NULL DEFAULT 0,
		`c_allow_fuentes` TINYINT NOT NULL DEFAULT 0,
		`c_ver_vistas_global` TINYINT NOT NULL DEFAULT 0,
		`c_quitar_vistas_global` TINYINT NOT NULL DEFAULT 0,
		`c_visitas_tiempo` TINYINT NOT NULL DEFAULT 5,
		`c_avatar` TINYINT NOT NULL DEFAULT 0,
		`leaving` TINYINT NOT NULL DEFAULT 0,
		`ads_300` TEXT DEFAULT NULL,
		`ads_468` TEXT DEFAULT NULL,
		`ads_160` TEXT DEFAULT NULL,
		`ads_728` TEXT DEFAULT NULL,
		`ads_search` VARCHAR(100) NOT NULL DEFAULT '',
		`c_last_active` TINYINT NOT NULL DEFAULT 3,
		`c_allow_sess_ip` TINYINT NOT NULL DEFAULT 1,
		`c_count_guests` TINYINT NOT NULL DEFAULT 0,
		`c_reg_active` TINYINT NOT NULL DEFAULT 1,
		`c_reg_activate` TINYINT NOT NULL DEFAULT 1,
		`c_reg_rango` INT NOT NULL DEFAULT 3,
		`c_met_welcome` TINYINT NOT NULL DEFAULT 0,
		`c_message_welcome` varchar(500) NOT NULL DEFAULT 'Hola [usuario], [welcome] a [b][web][/b].',
		`c_fotos_private` TINYINT NOT NULL DEFAULT 0,
		`c_hits_guest` TINYINT NOT NULL DEFAULT 0,
		`c_keep_points` TINYINT NOT NULL DEFAULT 0,
		`c_allow_points` TINYINT NOT NULL DEFAULT 0,
		`c_allow_edad` TINYINT NOT NULL DEFAULT 16,
		`c_max_posts` INT NOT NULL DEFAULT 16,
		`c_max_com` INT NOT NULL DEFAULT 25,
		`c_max_nots` INT NOT NULL DEFAULT 99,
		`c_max_acts` INT NOT NULL DEFAULT 99,
		`c_newr_type` TINYINT NOT NULL DEFAULT 0,
		`c_allow_sump` TINYINT NOT NULL DEFAULT 0,
		`c_allow_firma` TINYINT NOT NULL DEFAULT 1,
		`c_allow_upload` TINYINT NOT NULL DEFAULT 0,
		`c_allow_portal` TINYINT NOT NULL DEFAULT 1,
		`c_allow_live` TINYINT NOT NULL DEFAULT 1,
		`c_see_mod` TINYINT NOT NULL DEFAULT 0,
		`c_stats_cache` TINYINT NOT NULL DEFAULT 15,
		`c_desapprove_post` TINYINT NOT NULL DEFAULT 0,
		`offline` TINYINT NOT NULL DEFAULT 0,
		`offline_message` VARCHAR(255) NOT NULL DEFAULT 'Estamos en mantenimiento',
		`pkey` VARCHAR(72) NOT NULL DEFAULT '',
		`skey` VARCHAR(72) NOT NULL DEFAULT '',
		`version` VARCHAR(30) NOT NULL DEFAULT '',
		`version_code` VARCHAR(30) NOT NULL DEFAULT ''
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;"
];
